# -*- coding: utf-8 -*-
"""IIR_Butterworth_highpass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fbUpeLl0jqI9Iu8P-i3uvTSdXIh6d_K
"""

import numpy as np
from scipy.signal import butter, freqz
import matplotlib.pyplot as plt

# Filter parameters
fs = 1000  # Sampling frequency
cutoff = 100  # Cutoff frequency
order = 4  # Filter order

# Designing Butterworth high-pass filter coefficients
coefficients = butter(order, cutoff / (0.5 * fs), btype='high')  # Coefficients

# Computing the frequency response of the filter
freq_response = freqz(*coefficients, worN=2000)  # Frequency response

# Plotting the frequency response
fig, ax1 = plt.subplots()
ax1.set_title('Frekventni odziv highpass Butterworth filtera')
ax1.plot(0.5 * fs * freq_response[0] / np.pi, 20 * np.log10(np.abs(freq_response[1])), 'b')
ax1.set_ylabel('Amplituda [dB]', color='b')
ax1.set_xlabel('Frekvencija [Hz]')
ax1.set_ylim([-80, 5])
ax1.set_xlim([0, 0.5 * fs])
ax1.grid()

plt.show()