# -*- coding: utf-8 -*-
"""IIR_filter_ButterworthLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZbbOhXSnF1aj9p5d_6xIyISAIxLn5jz
"""

import numpy as np
from scipy.signal import butter, freqz
import matplotlib.pyplot as plt

# Filter parameters
fs = 1000  # Sampling frequency
cutoff = 100  # Cutoff frequency
order = 4  # Filter order

# Designing Butterworth filter and getting coefficients
coefficients = butter(order, cutoff / (fs / 2), btype='low')  # Filter coefficients

# Computing frequency response
freq_response = freqz(*coefficients, worN=8000)

# Plotting the results
plt.plot(freq_response[0] * fs / (2 * np.pi), 20 * np.log10(np.abs(freq_response[1])))
plt.title('Frekventni odziv lowpass Butterworth filtera')
plt.xlabel('Frekvencija [Hz]')
plt.ylabel('Amplituda [dB]')
plt.grid()
plt.ylim([-80, 5])
plt.xlim([0, fs / 2])
plt.show()